apiVersion: v1
kind: Service
metadata:
  name: ingest
  labels:
    app.kubernetes.io/name: omneval
    app.kubernetes.io/component: ingest
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: omneval
    app.kubernetes.io/component: ingest
