apiVersion: v1
kind: Service
metadata:
  name: query
  labels:
    app.kubernetes.io/name: lantern
    app.kubernetes.io/component: query
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: lantern
    app.kubernetes.io/component: query
