apiVersion: v1
kind: Service
metadata:
  name: writer
  labels:
    app.kubernetes.io/name: omneval
    app.kubernetes.io/component: writer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: omneval
    app.kubernetes.io/component: writer
